# Generated by Django 5.1.1 on 2024-10-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBSTANCIA', models.CharField(max_length=500)),
                ('CNPJ', models.CharField(max_length=500)),
                ('LABORATORIO', models.CharField(max_length=1000)),
            ],
        ),
    ]
